/*
 * SimaquaView.java
 */
package simaqua;

import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import simaqua.modelo.Aquario;
import simaqua.modelo.Atum;
import simaqua.modelo.CavaloMarinho;
import simaqua.modelo.Golfinho;
import simaqua.modelo.Sardinha;
import simaqua.modelo.Simulacao;
import simaqua.modelo.Siri;
import simaqua.modelo.Tubarao;

/**
 * The application's main frame.
 */
public class SimaquaView extends FrameView {

    /**
     * Objeto que inicia uma simulação
     */
    private Simulacao simulacao;

    /**
     * Construtor da janela principal. Apenas inicializa os componentes
     * @param app
     */
    public SimaquaView(SingleFrameApplication app) {
        super(app);
        initComponents();
    }

    /**
     * Retorna uma instancia do aquario. Esse método foi criado
     * para facilitar a conversão do atributo aquario (que é do tipo
     * JPanel) para a classe Aquario. Isso é necessário pois a interface
     * foi criada pelo netbeans, e portanto não é possível alterar seu
     * tipo de JPanel para aquario.
     * @return o aquario (que é também um JPanel)
     */
    private Aquario getAquario() {
        return (Aquario) aquario;
    }

    /**
     * Método chamado quando o usuário clica no botão "Iniciar".
     * Para uma simulação, inicializa o aquário, e inicia uma nova
     * simulação.
     * Ps: Uma simulação é uma Thread
     */
    private void iniciarSimulacao() {
        pararSimulacao();
        getAquario().inicializarAquario();
        simulacao = new Simulacao(getAquario());
        simulacao.start();
    }

    /**
     * Para uma simulação, se a mesma existir.
     */
    private void pararSimulacao() {
        if (simulacao != null) {
            simulacao.pararSimulacao();
        }
    }

    /**
     * Método auxiliar que retorna o número digitado pelo usuário
     * na caixa de texto "Quantidade"
     * @return um inteiro que representa a quantidade de seres a serem adicionados
     */
    private int getQuantidade() {
        return Integer.parseInt(jTextFieldQuantidade.getText());
    }

    /**
     * Método chamado quando o usuário clica em "Atum"
     */
    private void adicionarAtum() {
        for(int i = 0; i < getQuantidade(); i++)
            getAquario().adicionarSerMarinho(new Atum());
    }
    
    //teste
    
    /**
     * Método chamado quando o usuário clica em "Cavalo Marinho"
     */
    private void adicionarCavaloMarinho() {
         for(int i = 0; i < getQuantidade(); i++)
            getAquario().adicionarSerMarinho(new CavaloMarinho());
    }
    /**
     * Método chamado quando o usuário clica em "Golfinho"
     */
    private void adicionarGolfinho() {
        for(int i = 0; i < getQuantidade(); i++)
            getAquario().adicionarSerMarinho(new Golfinho());
    }
    /**
     * Método chamado quando o usuário clica em "Sardinha"
     */
    private void adicionarSardinha() {
        for(int i = 0; i < getQuantidade(); i++)
            getAquario().adicionarSerMarinho(new Sardinha());
    }
    /**
     * Método chamado quando o usuário clica em "Siri"
     */
    private void adicionarSiri() {
        for(int i = 0; i < getQuantidade(); i++)
            getAquario().adicionarSerMarinho(new Siri());
    }
    /**
     * Método chamado quando o usuário clica em "Tubarão"
     */
    private void adicionarTubarao() {        
        for(int i = 0; i < getQuantidade(); i++)
           getAquario().adicionarSerMarinho(new Tubarao()); 
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SimaquaApp.getApplication().getMainFrame();
            aboutBox = new SimaquaAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SimaquaApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        aquario = new simaqua.modelo.Aquario();
        jPanelControle = new javax.swing.JPanel();
        jButtonIniciarSimulacao = new javax.swing.JButton();
        jButtonPararSimulacao = new javax.swing.JButton();
        jButtonAtum = new javax.swing.JButton();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCavaloMarinho = new javax.swing.JButton();
        jButtonGolfinho = new javax.swing.JButton();
        jButtonSardinha = new javax.swing.JButton();
        jButtonTubarao = new javax.swing.JButton();
        jButtonSiri = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(simaqua.SimaquaApp.class).getContext().getResourceMap(SimaquaView.class);
        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        aquario.setBackground(resourceMap.getColor("aquario.background")); // NOI18N
        aquario.setForeground(resourceMap.getColor("aquario.foreground")); // NOI18N
        aquario.setFont(resourceMap.getFont("aquario.font")); // NOI18N
        aquario.setName("aquario"); // NOI18N

        javax.swing.GroupLayout aquarioLayout = new javax.swing.GroupLayout(aquario);
        aquario.setLayout(aquarioLayout);
        aquarioLayout.setHorizontalGroup(
            aquarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        aquarioLayout.setVerticalGroup(
            aquarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanelControle.setName("jPanelControle"); // NOI18N
        jPanelControle.setPreferredSize(new java.awt.Dimension(0, 0));

        jButtonIniciarSimulacao.setText(resourceMap.getString("jButtonIniciarSimulacao.text")); // NOI18N
        jButtonIniciarSimulacao.setName("jButtonIniciarSimulacao"); // NOI18N
        jButtonIniciarSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSimulacaoActionPerformed(evt);
            }
        });

        jButtonPararSimulacao.setText(resourceMap.getString("jButtonPararSimulacao.text")); // NOI18N
        jButtonPararSimulacao.setName("jButtonPararSimulacao"); // NOI18N
        jButtonPararSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararSimulacaoActionPerformed(evt);
            }
        });

        jButtonAtum.setText(resourceMap.getString("jButtonAtum.text")); // NOI18N
        jButtonAtum.setName("jButtonAtum"); // NOI18N
        jButtonAtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtumActionPerformed(evt);
            }
        });

        jTextFieldQuantidade.setText(resourceMap.getString("jTextFieldQuantidade.text")); // NOI18N
        jTextFieldQuantidade.setName("jTextFieldQuantidade"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButtonCavaloMarinho.setText(resourceMap.getString("jButtonCavaloMarinho.text")); // NOI18N
        jButtonCavaloMarinho.setName("jButtonCavaloMarinho"); // NOI18N
        jButtonCavaloMarinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCavaloMarinhoActionPerformed(evt);
            }
        });

        jButtonGolfinho.setText(resourceMap.getString("jButtonGolfinho.text")); // NOI18N
        jButtonGolfinho.setName("jButtonGolfinho"); // NOI18N
        jButtonGolfinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGolfinhoActionPerformed(evt);
            }
        });

        jButtonSardinha.setText(resourceMap.getString("jButtonSardinha.text")); // NOI18N
        jButtonSardinha.setName("jButtonSardinha"); // NOI18N
        jButtonSardinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSardinhaActionPerformed(evt);
            }
        });

        jButtonTubarao.setText(resourceMap.getString("jButtonTubarao.text")); // NOI18N
        jButtonTubarao.setName("jButtonTubarao"); // NOI18N
        jButtonTubarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTubaraoActionPerformed(evt);
            }
        });

        jButtonSiri.setText(resourceMap.getString("jButtonSiri.text")); // NOI18N
        jButtonSiri.setName("jButtonSiri"); // NOI18N
        jButtonSiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControleLayout = new javax.swing.GroupLayout(jPanelControle);
        jPanelControle.setLayout(jPanelControleLayout);
        jPanelControleLayout.setHorizontalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addComponent(jButtonGolfinho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTubarao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPararSimulacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIniciarSimulacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelControleLayout.createSequentialGroup()
                                .addComponent(jButtonAtum, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSardinha))
                            .addGroup(jPanelControleLayout.createSequentialGroup()
                                .addComponent(jButtonCavaloMarinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSiri)))))
                .addContainerGap())
        );
        jPanelControleLayout.setVerticalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciarSimulacao)
                    .addComponent(jButtonAtum)
                    .addComponent(jButtonSardinha))
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPararSimulacao))
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSiri)
                            .addComponent(jButtonCavaloMarinho)
                            .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTubarao)
                            .addComponent(jButtonGolfinho))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aquario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aquario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(simaqua.SimaquaApp.class).getContext().getActionMap(SimaquaView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setToolTipText(resourceMap.getString("exitMenuItem.toolTipText")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setToolTipText(resourceMap.getString("aboutMenuItem.toolTipText")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSimulacaoActionPerformed
        iniciarSimulacao();
    }//GEN-LAST:event_jButtonIniciarSimulacaoActionPerformed

    private void jButtonPararSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararSimulacaoActionPerformed
        pararSimulacao();
    }//GEN-LAST:event_jButtonPararSimulacaoActionPerformed

    private void jButtonAtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtumActionPerformed
        adicionarAtum();
    }//GEN-LAST:event_jButtonAtumActionPerformed

    private void jButtonCavaloMarinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCavaloMarinhoActionPerformed
        adicionarCavaloMarinho();
    }//GEN-LAST:event_jButtonCavaloMarinhoActionPerformed

    private void jButtonGolfinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGolfinhoActionPerformed
        adicionarGolfinho();
    }//GEN-LAST:event_jButtonGolfinhoActionPerformed

    private void jButtonSardinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSardinhaActionPerformed
        adicionarSardinha();
    }//GEN-LAST:event_jButtonSardinhaActionPerformed

    private void jButtonSiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiriActionPerformed
        adicionarSiri();
    }//GEN-LAST:event_jButtonSiriActionPerformed

    private void jButtonTubaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTubaraoActionPerformed
        adicionarTubarao();
    }//GEN-LAST:event_jButtonTubaraoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aquario;
    private javax.swing.JButton jButtonAtum;
    private javax.swing.JButton jButtonCavaloMarinho;
    private javax.swing.JButton jButtonGolfinho;
    private javax.swing.JButton jButtonIniciarSimulacao;
    private javax.swing.JButton jButtonPararSimulacao;
    private javax.swing.JButton jButtonSardinha;
    private javax.swing.JButton jButtonSiri;
    private javax.swing.JButton jButtonTubarao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelControle;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    private JDialog aboutBox;
}
